import { Extension, textInputRule } from "@tiptap/core"

/**
 * Extension based on:
 * - Tiptap Typography extension (https://tiptap.dev/api/extensions/typography)
 * - Tiptap SmilieReplacer example (https://tiptap.dev/examples/savvy)
 */

export default Extension.create({
    name: "shortcuts",
    priority: 500,

    addInputRules() {
        return [
            textInputRule({ find: /-- $/, replace: "— " }),
            textInputRule({ find: /\.{3}$/, replace: "…" }),
            textInputRule({ find: /←> $/, replace: "↔" }),
            textInputRule({ find: /<-$/, replace: "←" }),
            textInputRule({ find: /->$/, replace: "→" }),
            textInputRule({ find: /\(c\)$/, replace: "©" }),
            textInputRule({ find: /\(tm\)$/, replace: "™" }),
            textInputRule({ find: /\(r\)$/, replace: "®" }),
            textInputRule({ find: /1\/2 $/, replace: "½ " }),
            textInputRule({ find: /\+\/- $/, replace: "± " }),
            textInputRule({ find: /!= $/, replace: "≠ " }),
            textInputRule({ find: /<< $/, replace: "« " }),
            textInputRule({ find: />> $/, replace: "» " }),
            textInputRule({ find: /\^2 $/, replace: "² " }),
            textInputRule({ find: /\^3 $/, replace: "³ " }),
            textInputRule({ find: /1\/4 $/, replace: "¼ " }),
            textInputRule({ find: /3\/4 $/, replace: "¾ " }),

            /**
             * Smileys
             */
            textInputRule({ find: /-___- $/, replace: "😑 " }),
            textInputRule({ find: /:'-\) $/, replace: "😂 " }),
            textInputRule({ find: /':-\) $/, replace: "😅 " }),
            textInputRule({ find: /':-D $/, replace: "😅 " }),
            textInputRule({ find: />:-\) $/, replace: "😆 " }),
            textInputRule({ find: /-__- $/, replace: "😑 " }),
            textInputRule({ find: /':-\( $/, replace: "😓 " }),
            textInputRule({ find: /:'-\( $/, replace: "😢 " }),
            textInputRule({ find: />:-\( $/, replace: "😠 " }),
            textInputRule({ find: /O:-\) $/, replace: "😇 " }),
            textInputRule({ find: /0:-3 $/, replace: "😇 " }),
            textInputRule({ find: /0:-\) $/, replace: "😇 " }),
            textInputRule({ find: /0;\^\) $/, replace: "😇 " }),
            textInputRule({ find: /O;-\) $/, replace: "😇 " }),
            textInputRule({ find: /0;-\) $/, replace: "😇 " }),
            textInputRule({ find: /O:-3 $/, replace: "😇 " }),
            textInputRule({ find: /:'\) $/, replace: "😂 " }),
            textInputRule({ find: /:-D $/, replace: "😃 " }),
            textInputRule({ find: /':\) $/, replace: "😅 " }),
            textInputRule({ find: /'=\) $/, replace: "😅 " }),
            textInputRule({ find: /':D $/, replace: "😅 " }),
            textInputRule({ find: /'=D $/, replace: "😅 " }),
            textInputRule({ find: />:\) $/, replace: "😆 " }),
            textInputRule({ find: />;\) $/, replace: "😆 " }),
            textInputRule({ find: />=\) $/, replace: "😆 " }),
            textInputRule({ find: /;-\) $/, replace: "😉 " }),
            textInputRule({ find: /\*-\) $/, replace: "😉 " }),
            textInputRule({ find: /;-\] $/, replace: "😉 " }),
            textInputRule({ find: /;\^\) $/, replace: "😉 " }),
            textInputRule({ find: /B-\) $/, replace: "😎 " }),
            textInputRule({ find: /8-\) $/, replace: "😎 " }),
            textInputRule({ find: /B-D $/, replace: "😎 " }),
            textInputRule({ find: /8-D $/, replace: "😎 " }),
            textInputRule({ find: /:-\* $/, replace: "😘 " }),
            textInputRule({ find: /:\^\* $/, replace: "😘 " }),
            textInputRule({ find: /:-\) $/, replace: "🙂 " }),
            textInputRule({ find: /-_- $/, replace: "😑 " }),
            textInputRule({ find: /:-X $/, replace: "😶 " }),
            textInputRule({ find: /:-# $/, replace: "😶 " }),
            textInputRule({ find: /:-x $/, replace: "😶 " }),
            textInputRule({ find: />.< $/, replace: "😣 " }),
            textInputRule({ find: /:-O $/, replace: "😮 " }),
            textInputRule({ find: /:-o $/, replace: "😮 " }),
            textInputRule({ find: /O_O $/, replace: "😮 " }),
            textInputRule({ find: />:O $/, replace: "😮 " }),
            textInputRule({ find: /:-P $/, replace: "😛 " }),
            textInputRule({ find: /:-p $/, replace: "😛 " }),
            textInputRule({ find: /:-Þ $/, replace: "😛 " }),
            textInputRule({ find: /:-þ $/, replace: "😛 " }),
            textInputRule({ find: /:-b $/, replace: "😛 " }),
            textInputRule({ find: />:P $/, replace: "😜 " }),
            textInputRule({ find: /X-P $/, replace: "😜 " }),
            textInputRule({ find: /x-p $/, replace: "😜 " }),
            textInputRule({ find: /':\( $/, replace: "😓 " }),
            textInputRule({ find: /'=\( $/, replace: "😓 " }),
            textInputRule({ find: />:\\ $/, replace: "😕 " }),
            textInputRule({ find: />:\/ $/, replace: "😕 " }),
            textInputRule({ find: /:-\/ $/, replace: "😕 " }),
            textInputRule({ find: /:-. $/, replace: "😕 " }),
            textInputRule({ find: />:\[ $/, replace: "😞 " }),
            textInputRule({ find: /:-\( $/, replace: "😞 " }),
            textInputRule({ find: /:-\[ $/, replace: "😞 " }),
            textInputRule({ find: /:'\( $/, replace: "😢 " }),
            textInputRule({ find: /;-\( $/, replace: "😢 " }),
            textInputRule({ find: /#-\) $/, replace: "😵 " }),
            textInputRule({ find: /%-\) $/, replace: "😵 " }),
            textInputRule({ find: /X-\) $/, replace: "😵 " }),
            textInputRule({ find: />:\( $/, replace: "😠 " }),
            textInputRule({ find: /0:3 $/, replace: "😇 " }),
            textInputRule({ find: /0:\) $/, replace: "😇 " }),
            textInputRule({ find: /O:\) $/, replace: "😇 " }),
            textInputRule({ find: /O=\) $/, replace: "😇 " }),
            textInputRule({ find: /O:3 $/, replace: "😇 " }),
            textInputRule({ find: /<\/3 $/, replace: "💔 " }),
            textInputRule({ find: /:D $/, replace: "😃 " }),
            textInputRule({ find: /=D $/, replace: "😃 " }),
            textInputRule({ find: /;\) $/, replace: "😉 " }),
            textInputRule({ find: /\*\) $/, replace: "😉 " }),
            textInputRule({ find: /;\] $/, replace: "😉 " }),
            textInputRule({ find: /;D $/, replace: "😉 " }),
            textInputRule({ find: /B\) $/, replace: "😎 " }),
            textInputRule({ find: /8\) $/, replace: "😎 " }),
            textInputRule({ find: /:\* $/, replace: "😘 " }),
            textInputRule({ find: /=\* $/, replace: "😘 " }),
            textInputRule({ find: /:\) $/, replace: "🙂 " }),
            textInputRule({ find: /=\] $/, replace: "🙂 " }),
            textInputRule({ find: /=\) $/, replace: "🙂 " }),
            textInputRule({ find: /:\] $/, replace: "🙂 " }),
            textInputRule({ find: /:X $/, replace: "😶 " }),
            textInputRule({ find: /:# $/, replace: "😶 " }),
            textInputRule({ find: /=X $/, replace: "😶 " }),
            textInputRule({ find: /=x $/, replace: "😶 " }),
            textInputRule({ find: /:x $/, replace: "😶 " }),
            textInputRule({ find: /=# $/, replace: "😶 " }),
            textInputRule({ find: /:O $/, replace: "😮 " }),
            textInputRule({ find: /:o $/, replace: "😮 " }),
            textInputRule({ find: /:P $/, replace: "😛 " }),
            textInputRule({ find: /=P $/, replace: "😛 " }),
            textInputRule({ find: /:p $/, replace: "😛  " }),
            textInputRule({ find: /=p $/, replace: "😛 " }),
            textInputRule({ find: /:Þ $/, replace: "😛 " }),
            textInputRule({ find: /:þ $/, replace: "😛 " }),
            textInputRule({ find: /:b $/, replace: "😛 " }),
            textInputRule({ find: /d: $/, replace: "😛 " }),
            textInputRule({ find: /:\/ $/, replace: "😕 " }),
            textInputRule({ find: /:\\ $/, replace: "😕 " }),
            textInputRule({ find: /=\/ $/, replace: "😕 " }),
            textInputRule({ find: /=\\ $/, replace: "😕 " }),
            textInputRule({ find: /:L $/, replace: "😕 " }),
            textInputRule({ find: /=L $/, replace: "😕 " }),
            textInputRule({ find: /:\( $/, replace: "😞 " }),
            textInputRule({ find: /:\[ $/, replace: "😞 " }),
            textInputRule({ find: /=\( $/, replace: "😞 " }),
            textInputRule({ find: /;\( $/, replace: "😢 " }),
            textInputRule({ find: /D: $/, replace: "😨 " }),
            textInputRule({ find: /:\$ $/, replace: "😳 " }),
            textInputRule({ find: /=\$ $/, replace: "😳 " }),
            textInputRule({ find: /#\) $/, replace: "😵 " }),
            textInputRule({ find: /%\) $/, replace: "😵 " }),
            textInputRule({ find: /X\) $/, replace: "😵 " }),
            textInputRule({ find: /:@ $/, replace: "😠 " }),
            textInputRule({ find: /<3 $/, replace: "❤️ " }),
            textInputRule({ find: /\/shrug $/, replace: "¯\\_(ツ)_/¯" })
        ]
    }
})
