import { useSession } from 'next-auth/react'
import Router from 'next/router'

import Link from 'next/link'
import Head from 'next/head'

import styles from "../styles/Auth.module.css"

export default function AuthLayout({ children }) {
    const { data: session } = useSession()
    if (session === undefined) {
        return null
    } else if (session) {
        Router.push("/")
        return null
    }

    return (
        <>
            <Head>
                <title>SlashWriter - Authentification</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="content">
                <div className={styles.logo}>
                    <Link href="/">
                        <a>
                            <picture>
                                <source srcSet="/assets/logo.svg" media="(max-width: 600px)" />
                                <img src="/assets/logoFull.svg" alt="Logo SlashWriter" />
                            </picture>
                        </a>
                    </Link>
                </div>
                <main>
                    {children}
                </main>
            </div>
        </>
    )
}
