import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { RiGithubFill } from "react-icons/ri"
import Flex from "src/components/Flex"
import Button from "src/components/ui/Button"
import Typography from "src/components/ui/Typography"
import { withoutPageAuth } from "src/utils/supabase"
import styled from "styled-components"

function Home() {
    return (
        <>
            <Head>
                <title>SlashWriter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <Header>
                    <Image
                        src="/assets/logo.svg"
                        width={180}
                        height={50}
                        alt="logo"
                        id="logo"
                    />
                    <nav>
                        <Link href="https://slashwriter.fly.dev/doc/1ce53e87-bbf3-4676-b657-2212a8f4ba74">
                            Démo
                        </Link>
                        <Link href="/auth">Connexion</Link>
                    </nav>
                </Header>
                <Hero>
                    <Typography.Title
                        level={1}
                        style={{ textAlign: "center", maxWidth: 500 }}
                    >
                        Prise de notes simple et élégante.
                    </Typography.Title>
                    <Typography.Text
                        align="center"
                        style={{ fontSize: "1.2rem", maxWidth: 300 }}
                    >
                        Créez, organisez et partagez vos notes avec Slashwriter.
                    </Typography.Text>
                    <Flex
                        gap={10}
                        style={{ flexWrap: "wrap", justifyContent: "center" }}
                    >
                        <Link
                            target="_blank"
                            href="https://slashwriter.fly.dev/doc/1ce53e87-bbf3-4676-b657-2212a8f4ba74"
                        >
                            <Button size="large">Essayer la démo</Button>
                        </Link>
                        <Link
                            target="_blank"
                            href="https://github.com/pierre-lgb/slashwriter"
                        >
                            <Button
                                appearance="secondary"
                                size="large"
                                icon={<RiGithubFill />}
                            >
                                Code source
                            </Button>
                        </Link>
                    </Flex>

                    <img
                        src="/assets/slashwriter-mockup.png"
                        alt="cover"
                        id="cover"
                    />
                </Hero>
                <FeatureList>
                    <Feature>
                        <FeatureImage
                            style={{
                                backgroundImage:
                                    "url(/assets/slashwriter-commands-preview.gif)"
                            }}
                        ></FeatureImage>
                        <FeatureDetails>
                            <Typography.Title level={3}>
                                Commandes
                            </Typography.Title>
                            <Typography.Text>
                                En écrivant{" "}
                                <Typography.Text code small>
                                    /
                                </Typography.Text>
                                {` dans l'éditeur, une liste de commandes apparaît pour vous permettre de rapidement ajouter des titres, des images, des tableaux et bien plus encore, sans avoir à chercher dans des menus.`}
                            </Typography.Text>
                        </FeatureDetails>
                    </Feature>
                    <Feature reverse>
                        <FeatureImage
                            style={{
                                backgroundImage:
                                    "url(/assets/slashwriter-collaboration-preview.gif)"
                            }}
                        ></FeatureImage>
                        <FeatureDetails>
                            <Typography.Title level={3}>
                                Éditeur Collaboratif
                            </Typography.Title>
                            <Typography.Text>
                                {`Slashwriter permet de travailler en
                                collaboration sur des documents en temps réel.
                                Vous pouvez inviter d'autres utilisateurs à
                                modifier ou commenter votre document, et voir
                                leurs modifications en temps réel.`}
                            </Typography.Text>
                        </FeatureDetails>
                    </Feature>
                    <Feature>
                        <FeatureImage
                            style={{
                                backgroundImage:
                                    "url(/assets/slashwriter-subpages-preview.gif)"
                            }}
                        ></FeatureImage>
                        <FeatureDetails>
                            <Typography.Title level={3}>
                                Pages intégrées
                            </Typography.Title>
                            <Typography.Text>
                                {`Slashwriter permet d'organiser vos documents
                                en utilisant des sous-documents intégrés. Cela
                                permet de rendre la navigation et la lecture
                                plus aisées, en évitant de devoir faire défiler
                                un document long et complexe.`}
                            </Typography.Text>
                        </FeatureDetails>
                    </Feature>
                    <Feature reverse>
                        <FeatureImage
                            style={{
                                backgroundImage:
                                    "url(/assets/slashwriter-equations-preview.gif)"
                            }}
                        ></FeatureImage>
                        <FeatureDetails>
                            <Typography.Title level={3}>
                                Équations
                            </Typography.Title>
                            <Typography.Text>
                                Slashwriter prend en charge les équations
                                mathématiques. Vous pouvez facilement ajouter
                                des équations en utilisant la syntaxe LaTeX, ce
                                qui permet de créer des documents de meilleure
                                qualité.
                            </Typography.Text>
                        </FeatureDetails>
                    </Feature>
                    <Feature>
                        <FeatureImage
                            style={{
                                backgroundImage:
                                    "url(/assets/slashwriter-tables-preview.gif)"
                            }}
                        ></FeatureImage>
                        <FeatureDetails>
                            <Typography.Title level={3}>
                                Tableaux
                            </Typography.Title>
                            <Typography.Text>
                                Slashwriter vous permet également de créer et
                                modifier des tableaux avec une structure simple.
                                Vous pouvez facilement modifier les couleurs,
                                rajouter des lignes et des colonnes, etc.
                            </Typography.Text>
                        </FeatureDetails>
                    </Feature>
                </FeatureList>
                <Footer>
                    <Typography.Text style={{ color: "#9C9C9C" }}>
                        Slashwriter. Développé par Pierre L.
                    </Typography.Text>
                    <Typography.Link
                        target="_blank"
                        href="https://github.com/pierre-lgb/slashwriter"
                    >
                        Code source (Github)
                    </Typography.Link>
                </Footer>
            </Container>
        </>
    )
}

const Container = styled.div`
    min-width: 300px;
    background: linear-gradient(90deg, #eaeaea 1px, transparent 1px) 1px 0, #fff;
    background-size: calc(100% / 4) 1px;
    background-position: center;
`

const Header = styled.header`
    display: flex;
    justify-content: space-between;
    padding: 3rem 5rem;

    nav {
        display: flex;
        align-items: center;
        gap: 20px;
    }

    @media screen and (max-width: 550px) {
        #logo {
            display: none;
        }

        justify-content: center;
    }
`

const Hero = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 20px 50px;
    gap: 20px;

    #cover {
        width: 90%;
        @media screen and (max-width: 550px) {
            width: 120%;
        }
    }
`

const FeatureList = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 100px;
    margin: 100px 0;
`

const Feature = styled.div<{ reverse?: boolean }>`
    display: flex;
    gap: 50px;
    max-width: 1100px;
    width: 90%;
    justify-content: center;
    align-items: center;

    @media screen and (max-width: 768px) {
        max-width: 500px;
        width: 100%;
    }

    flex-direction: ${(props) => (props.reverse ? "row-reverse" : "row")};

    @media (max-width: 768px) {
        flex-direction: column;
        align-items: center;
        gap: 10px;
    }

    text-align: ${(props) => (props.reverse ? "right" : "left")};
`

const FeatureImage = styled.div`
    width: 50%;
    height: 300px;
    background-color: #eeeeee;
    background-size: cover;
    background-position: left bottom;
    flex-shrink: 0;
    border: 15px solid #fff;
    border-radius: 0.125rem;
    box-shadow: 0px 0px 0px 1px #eaeaea;

    @media screen and (max-width: 768px) {
        width: 80%;
    }
`

const FeatureDetails = styled.div`
    width: 50%;

    @media screen and (max-width: 768px) {
        width: 80%;
    }
`

const Footer = styled.div`
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin-top: 200px;
    height: 150px;
    background-color: #eaeaea;
`

export const getServerSideProps = withoutPageAuth()

export default Home
