import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Flex from 'src/components/Flex'
import { withoutPageAuth } from 'src/utils/supabase'
import styled from 'styled-components'

function Home() {
    return (
        <Container>
            <Head>
                <title>SlashWriter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Main align="center" justify="center">
                <Link href="/auth">Connexion</Link>
            </Main>
        </Container>
    )
}

const Container = styled.div`
    padding: 2rem;
`

const Main = styled(Flex)`
    height: 100%;
`

export const getServerSideProps = withoutPageAuth()

export default Home
