import { signOut, useSession } from 'next-auth/react'
import Router from 'next/router'

import Head from 'next/head'
import Link from 'next/link'
import Logo from '../../components/svgs/Logo'
import SettingsIcon from '../../components/svgs/SettingsIcon'
import NotificationsIcon from '../svgs/NotificationsIcon'
import WorkspacesIcon from '../svgs/WorkspacesIcon'
import ExploreIcon from '../svgs/ExploreIcon'

import styles from "../../styles/layouts/MainLayout.module.css"

export default function MainLayout({ children }) {
    const { data: session } = useSession()
    if (session === undefined) {
        return null
    } else if (session === null) {
        Router.push("/")
        return null
    }

    return (
        <>
            <Head>
                <title>SlashWriter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <nav id="sidebar" className={styles.sidebar}>
                    <Logo width="42px" height="42px" />
                    <div className={styles.sidebarMiddle}>
                        <Link href="/explore">
                            <a className={styles.sidebarLink}><ExploreIcon /></a>
                        </Link>
                        <Link href="/workspaces">
                            <a className={styles.sidebarLink}><WorkspacesIcon /></a>
                        </Link>
                        <Link href="/account/notifications">
                            <a className={styles.sidebarLink}><NotificationsIcon /></a>
                        </Link>
                    </div>
                    <Link href="/account/settings">
                        <a className={styles.sidebarLink}><SettingsIcon /></a>
                    </Link>
                </nav>
                <div className={styles.header}>
                    <div className={styles.headerLeft}>
                        <div className={styles.navigationArrows}>

                        </div>
                        <div className={styles.tabs}>

                        </div>
                    </div>
                    <div className={styles.headerRight}>

                        <button
                            onClick={() => {
                                Router.push("/auth/signed-out")
                                signOut({ redirect: false })
                            }}
                            className={styles.logoutBtn}
                            title="Déconnexion"
                        ></button>
                        <div className={styles.avatar}>

                        </div>
                    </div>
                </div>
                <main>
                    {children}
                </main>
            </div>
        </>
    )
}
