import { logOut } from "../firebase/auth";
import { useRouter } from "next/router";
import { useAuthUser } from "next-firebase-auth";

import Head from "next/head";
import Link from "next/link";
import NotificationsIcon from "../components/svgs/NotificationsIcon";
import WorkspacesIcon from "../components/svgs/WorkspacesIcon";

import styles from "../../styles/layouts/MainLayout.module.css";
import SearchIcon from "../components/svgs/SearchIcon";

const Sidebar = () => {
    const router = useRouter();
    const user = useAuthUser();

    return (
        <nav id="sidebar" className={styles.sidebar}>
            <div className={styles.sidebarProfileSection}>
                {user && (
                    <>
                        <div className={styles.avatar}></div>
                        <div className={styles.username}>
                            {user.displayName}
                        </div>
                        {/* TODO : ↓ Chevron à la place + Tippy [Déconnexion / Paramètres] */}
                        <div
                            className={styles.moreBtn}
                            onClick={() => logOut()}
                        ></div>
                    </>
                )}
            </div>
            <div className={styles.linksSection}>
                <Link href="/search">
                    <a
                        data-active={router?.pathname === "/search"}
                        className={styles.sidebarLink}
                    >
                        <div className={styles.iconWrapper}>
                            <SearchIcon />
                        </div>
                        <div>Rechercher</div>
                    </a>
                </Link>
                <Link href="/notifications">
                    <a
                        data-active={router?.pathname === "/notifications"}
                        className={styles.sidebarLink}
                    >
                        <div className={styles.iconWrapper}>
                            <NotificationsIcon />
                        </div>
                        <div>Notifications</div>
                    </a>
                </Link>
                <Link href="/shared">
                    <a
                        data-active={router?.pathname === "/shared"}
                        className={styles.sidebarLink}
                    >
                        <div className={styles.iconWrapper}>
                            <NotificationsIcon />
                        </div>
                        <div>Partagé avec moi</div>
                    </a>
                </Link>
                <Link href="/spaces">
                    <a
                        data-active={router?.pathname === "/spaces"}
                        className={styles.sidebarLink}
                    >
                        <div className={styles.iconWrapper}>
                            <WorkspacesIcon />
                        </div>
                        <div>Mes espaces</div>
                    </a>
                </Link>
            </div>
            {/* <Logo width="42px" height="42px" />
            <div className={styles.sidebarMiddle}>
                <Link href="/explore">
                    <a className={styles.sidebarLink}>
                        <ExploreIcon />
                    </a>
                </Link>
                <Link href="/workspaces">
                    <a className={styles.sidebarLink}>
                        <WorkspacesIcon />
                    </a>
                </Link>
                <Link href="/account/notifications">
                    <a className={styles.sidebarLink}>
                        <NotificationsIcon />
                    </a>
                </Link>
            </div>
            <Link href="/account/settings">
                <a className={styles.sidebarLink}>
                    <SettingsIcon />
                </a>
            </Link> */}
        </nav>
    );
};

function MainLayout({ children, pageTitle }) {
    return (
        <>
            <Head>
                <title>{pageTitle || "SlashWriter"}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.container}>
                <Sidebar />
                {/* <div className={styles.header}>
                    <div className={styles.headerLeft}>
                        <div className={styles.navigationArrows}></div>
                        <div className={styles.tabs}></div>
                    </div>
                    <div className={styles.headerRight}>
                        <button
                            onClick={() => {
                                // TODO : Toast "Vous avez été déconnecté"
                                logOut();
                            }}
                            className={styles.logoutBtn}
                            title="Déconnexion"
                        ></button>
                        <div className={styles.avatar}></div>
                    </div>
                </div> */}
                <main className={styles.main}>{children}</main>
            </div>
        </>
    );
}

export default MainLayout;
